# Project
version=0.2.1
group=com.nyfaria.petshop
java_version=17

# Common
minecraft_version=1.20.1
minecraft_version_range=[1.20,1.21)

# Mod options
mod_name=Pet Shop
mod_author=Nyfaria and SirJain
mod_id=petshop
description=Adds various pets with realistic behavior and shops which sell pet-related items and cosmetics!
license=ARR
credits=

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Publishing
curseforge_publishing_enabled=true
curseforge_project_id=958623
modrinth_publishing_enabled=true
modrinth_project_id=82sacNxj
dry_run=false
